//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedVehicleSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle : Common
    {
        public string VehicleId { get; set; }
        public Nullable<int> MakeId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        //public System.DateTime CreateDate { get; set; }
        //public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
    }
}
