//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedVehicleSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel : Common
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleModel()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int ModelId { get; set; }
        public Nullable<int> EngineSize { get; set; }
        public Nullable<int> NumberOfDoors { get; set; }
        public string Colour { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        //public System.DateTime CreateDate { get; set; }
        //public Nullable<System.DateTime> EditDate { get; set; }
        public string ModelName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
